[package]
name = "color-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = [
    "io-util",
    "io-std",
    "macros",
    "rt-multi-thread",
] }
tower-lsp = "0.20.0"
csscolorparser = "0.7"
